### ISSUE TITLE
Is there any way to avoid the required use of git when I do "kcm apply"?

### ISSUE THREAD

**Issue by sir-gon** [Maples7/kong-config-manager#1]
I want to use KCM in my CI pipeline.

To do "apply", I need to run "kcm apply" in a non-git directory (my deployment is just a checkout without a .git in the directory inside due a security good-practice).

When I run KCM without the .git directory I get:

```
Not a git repository
To compare two paths outside a working tree:
usage: git diff [--no-index] <path> <path>

[ERROR] dir ./main does NOT exist for instance main
```

Additionally, if git is required to do "apply", my docker image needs git as additional dependency.

I have currently tracked my KONG configurations inside a large git project, but I don't want to mix this project with a "sub-repository" just for KONG config.

**Comment by Maples7** [comment]
Git is highly recommended for this tool unless you know exactly what you are doing. But it's true it can work without git.

I'll provide a option to block git warning like `kcm apply --without-git`, how's it like?

**Comment by Maples7** [comment]
I've release v1.6.0 and you can use `--no-git` to get rid of `Git`.

**Comment by Maples7** [comment]
https://github.com/Maples7/kong-config-manager/releases/tag/v1.6.0
