### ISSUE TITLE
Dump keys and credentials?

### ISSUE THREAD

**Issue by zoobab** [Maples7/kong-config-manager#6]
Hi,

I have dumped the content of my kong-admin, but I cannot find the keys and credentials, is there a way to dump those?

Best

**Comment by Maples7** [comment]
https://github.com/Maples7/kong-config-manager/blob/master/enums/index.js

`credentials` is always here, but is `keys`  from plugin [`Key Authentication`](https://docs.konghq.com/hub/kong-inc/key-auth/)? In fact, you could try to list all objects you want in your [configuration file](https://github.com/Maples7/kong-config-manager#cli-configuration-file). Once the `keys` object has basic CURD form, it should work fine.
