### ISSUE TITLE
Plugins are executed before the services

### ISSUE THREAD

**Issue by eturan** [Maples7/kong-config-manager#9]
Hi,

I have services, routes and one plugin in my config. One plugin attached to the service.

When I execute kcm apply commend against newly bootstrapped kong-database, I'm getting the following error

Request for POST - http://kong:8001/plugins gets response StatusCodeError: 400 - {"message":"the foreign key '{id=\"53b57092-4c99-436b-a3cd-5dc33f592d67\"}' does not reference an existing 'services' entity.","name":"foreign key violation","fields":{"service":{"id":"53b57092-4c99-436b-a3cd-5dc33f592d67"}},"code":4} but NOT 2xx

I believe plugins are being inserted before the services, if I execute the same command without any change, it works perfectly.

Is there any way to change this order?

Thank you in advance!

**Comment by Maples7** [comment]
Hey there! That's quit a problem, I'll make a patch and release an edition to make `plugins` applied after `services`.

**Comment by eturan** [comment]
Thank you for the very fast response. 

Good luck!

**Comment by Maples7** [comment]
Hey, I have updated master to https://github.com/Maples7/kong-config-manager/commit/a6accd1371529037c4293c509af2b487de241706 which passes all unit tests, could you please test it in your local environment via `git@github.com:Maples7/kong-config-manager.git && cd kong-config-manager && npm link`?

**Comment by Maples7** [comment]
If it's proved solved, I'll release a new patch edition to [NPM](https://www.npmjs.com/).

**Comment by eturan** [comment]
yes it works!

thank you :)

**Comment by Maples7** [comment]
Great! Then [v1.7.1](https://www.npmjs.com/package/kong-config-manager) is for you! 💯
